/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas4;

import coba.coba.MainFrm.DlgHelp;
import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author adianagustia
 */
public class FrmCuaca extends javax.swing.JFrame {

    /**
     * Creates new form FrmCuaca
     */
    public FrmCuaca() {
        initComponents();
        angin.setText("");
        lembap.setText("");
        maks.setText("");
        min.setText("");
        tekanan.setText("");
        suhu.setText("");
        lblKota.setText("Cuaca di Kota"+"");
    }
    
    public Connection getConnection() {
    Connection con;
    
    try{
        con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/p3_java4", "root", "");
        return con;
    }catch(SQLException e){
        return null; 
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtKota = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblKota = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        maks = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        angin = new javax.swing.JLabel();
        lembap = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tekanan = new javax.swing.JLabel();
        hari2 = new javax.swing.JLabel();
        Kalender = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        suhu = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblGambar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("kota");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 29, 39, -1));

        txtKota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKotaActionPerformed(evt);
            }
        });
        getContentPane().add(txtKota, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 29, 277, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblKota.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblKota.setText("MONITOR CUACA");
        jPanel1.add(lblKota, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 13, 230, -1));

        jLabel4.setText("Suhu Maksimum");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 87, -1, -1));

        jLabel5.setText("Suhu Minimum");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 109, -1, -1));

        jLabel6.setText("Kecepatan Angin");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 129, -1, -1));

        jLabel7.setText("Kelembapan");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 149, -1, -1));

        maks.setText("  ");
        jPanel1.add(maks, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 59, -1));

        min.setText("  ");
        jPanel1.add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 59, -1));

        angin.setText("  ");
        jPanel1.add(angin, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 59, -1));

        lembap.setText("  ");
        jPanel1.add(lembap, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 59, -1));

        jLabel16.setText("Tekanan Udara");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 169, -1, -1));

        tekanan.setText("  ");
        jPanel1.add(tekanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 59, -1));

        hari2.setText("  ");
        jPanel1.add(hari2, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 54, 160, -1));
        jPanel1.add(Kalender, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 20, 150, -1));

        jButton1.setText("Tampil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        suhu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(suhu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 130, 40));

        jLabel3.setText("Status Cuaca");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 193, -1, -1));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 69, 14));
        jPanel1.add(lblGambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 180, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 570, 235));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas4/Background.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 310));

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Exit");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem2.setText("Help");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("About");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Login");

        jMenuItem4.setText("Login");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKotaActionPerformed
        // TODO add your handling code here:
        
                
    }//GEN-LAST:event_txtKotaActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Aplikasi Monitoring Cuaca" + "\n Trisno" + "\n 1641811");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        DlgHelp help = new DlgHelp();
        help.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        FrmLogin input = new FrmLogin();
        input.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = getConnection();
            String input = txtKota.getText();
            SimpleDateFormat fmt = new SimpleDateFormat("YYYY-MM-dd");
            String tanggal = fmt.format(Kalender.getDate());

            Statement st = con.createStatement();
            String query = "SELECT * FROM t_cuaca WHERE nama_kota = '" + input +"' "
            + "AND Tanggal = '" + tanggal + "%' "
            + "LIMIT 1";
            ResultSet rs = st.executeQuery(query);

            while(rs.next()){
                //lblHari.setText(cbHari.getSelectedItem().toString());
                SimpleDateFormat fmt2 = new SimpleDateFormat("dd MMMM YYYY", Locale.forLanguageTag("Id"));
                hari2.setText(fmt2.format(Kalender.getDate()));
                lblKota.setText("Cuaca di "+rs.getString("nama_kota"));
                maks.setText(rs.getString("suhu_maks")+" "+(char)0x00B0+" C");
                min.setText(rs.getString("suhu_min")+" "+(char)0x00B0+" C");
                angin.setText(rs.getString("kecepatan_angin")+" m/s");
                lembap.setText(rs.getString("kelembapan")+" %");
                tekanan.setText(rs.getString("kecepatan_udara")+" hPa");
                suhu.setText(rs.getString("suhu")+" "+(char)0x00B0+" C");
                String gambar = rs.getString("gambar");
                jLabel8.setText(rs.getString("status"));
                //String gambar2 = "C:\\Users\\acer\\Desktop\\Tugas4\\src\\gambar_cuaca\\"+gambar;
                //lblGambar.setIcon(new javax.swing.ImageIcon(getClass().getResource(gambar2)));
                lblGambar.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Desktop\\Tugas4\\src\\gambar_cuaca\\"+gambar));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmCuaca.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Kalender;
    private javax.swing.JLabel angin;
    private javax.swing.JLabel hari2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblGambar;
    private javax.swing.JLabel lblKota;
    private javax.swing.JLabel lembap;
    private javax.swing.JLabel maks;
    private javax.swing.JLabel min;
    private javax.swing.JLabel suhu;
    private javax.swing.JLabel tekanan;
    private javax.swing.JTextField txtKota;
    // End of variables declaration//GEN-END:variables
}
