/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas4;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JTextField;
/**
 *
 * @author acer
 */
public class FrmInputData extends javax.swing.JFrame {

    /**
     * Creates new form FrmInputData
     */
    public FrmInputData() {
        initComponents();
    }
    
    public Connection getConnection() {
    Connection con;
    
    try{
        con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/p3_java4", "root", "");
        return con;
    }catch(SQLException e){
        return null; 
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtSuhu = new javax.swing.JTextField();
        txtMaks = new javax.swing.JTextField();
        txtMin = new javax.swing.JTextField();
        txtAngin = new javax.swing.JTextField();
        txtLembap = new javax.swing.JTextField();
        txtUdara = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnUp = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        calTanggal = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        status = new javax.swing.JTextField();
        gambar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Input Data Cuaca");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel2.setText("Tanggal");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 61, -1, -1));

        jLabel3.setText("Nama Kota");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 92, -1, -1));

        jLabel4.setText("Suhu");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel5.setText("Suhu Maks");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 151, -1, -1));

        jLabel6.setText("Suhu Min");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 182, -1, -1));

        jLabel7.setText("Kecepatan Angin");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 213, -1, -1));

        jLabel8.setText("Kelembapan");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 244, -1, -1));

        jLabel9.setText("Tekanan Udara");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 275, -1, -1));
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 89, 144, -1));
        getContentPane().add(txtSuhu, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 117, 144, -1));
        getContentPane().add(txtMaks, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 148, 144, -1));
        getContentPane().add(txtMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 179, 144, -1));
        getContentPane().add(txtAngin, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 210, 144, -1));
        getContentPane().add(txtLembap, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 241, 144, -1));
        getContentPane().add(txtUdara, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 272, 144, -1));

        jButton1.setText("Input");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, -1, -1));

        btnUp.setText("Update");
        btnUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpActionPerformed(evt);
            }
        });
        getContentPane().add(btnUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 370, -1, -1));

        btnDel.setText("Delete");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        getContentPane().add(btnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 58, 52, -1));

        jLabel10.setText("ID");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 61, -1, -1));

        calTanggal.setDateFormatString("yyyy-MM-dd");
        calTanggal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                calTanggalKeyPressed(evt);
            }
        });
        getContentPane().add(calTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 58, 142, -1));

        jButton2.setText("Gambar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 370, -1, -1));

        jLabel11.setText("Status");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 306, -1, -1));

        jLabel12.setText("Gambar");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 337, -1, -1));
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 303, 144, -1));
        getContentPane().add(gambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 334, 144, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas4/BInput.jpg"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            
            Connection con = getConnection();
            String query = "insert into t_cuaca (Tanggal,nama_kota,suhu,suhu_maks,suhu_min,kecepatan_angin,kelembapan,kecepatan_udara,status,gambar) values (?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement ps = con.prepareStatement(query);
            
            ps.setString(1, ((JTextField)calTanggal.getDateEditor().getUiComponent()).getText());
            ps.setString(2, txtNama.getText());
            ps.setString(3, txtSuhu.getText());
            ps.setString(4, txtMaks.getText());
            ps.setString(5, txtMin.getText());
            ps.setString(6, txtAngin.getText());
            ps.setString(7, txtLembap.getText());
            ps.setString(8, txtUdara.getText());
            ps.setString(9, status.getText());
            ps.setString(10, gambar.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Berhasil Di Input");
        }catch (Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
        try{
            
            Connection con = getConnection();
            String query = "DELETE from t_cuaca where ID=?";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, txtID.getText());
            
            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Berhasil Di delete");
        }catch (Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpActionPerformed
        // TODO add your handling code here:
                try{
            
            Connection con = getConnection();
            String query = "UPDATE t_cuaca set Tanggal=?,nama_kota=?,suhu=?,suhu_maks=?,suhu_min=?,kecepatan_angin=?,kelembapan=?,kecepatan_udara=?,status=?,gambar=? where id=?";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, ((JTextField)calTanggal.getDateEditor().getUiComponent()).getText());
            ps.setString(2, txtNama.getText());
            ps.setString(3, txtSuhu.getText());
            ps.setString(4, txtMaks.getText());
            ps.setString(5, txtMin.getText());
            ps.setString(6, txtAngin.getText());
            ps.setString(7, txtLembap.getText());
            ps.setString(8, txtUdara.getText());
            ps.setString(11, txtID.getText());
            ps.setString(9, status.getText());
            ps.setString(10, gambar.getText());
            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Berhasil Di update");
        }catch (Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }//GEN-LAST:event_btnUpActionPerformed

    private void calTanggalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_calTanggalKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_calTanggalKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser("C:\\Users\\acer\\Desktop\\Tugas4\\src\\gambar_cuaca\\");
        jfc.showOpenDialog(null);
        File file = jfc.getSelectedFile();
        String dir = file.getName();
        gambar.setText(dir);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnUp;
    private com.toedter.calendar.JDateChooser calTanggal;
    private javax.swing.JTextField gambar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField status;
    private javax.swing.JTextField txtAngin;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLembap;
    private javax.swing.JTextField txtMaks;
    private javax.swing.JTextField txtMin;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtSuhu;
    private javax.swing.JTextField txtUdara;
    // End of variables declaration//GEN-END:variables
}
