/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas4;

import com.mysql.jdbc.Connection;

import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author acer
 */
public class FrmKoneksi extends javax.swing.JFrame {

    /**
     * Creates new form FrmKoneksi
     */
    public FrmKoneksi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fieldDB = new javax.swing.JTextField();
        fieldUser = new javax.swing.JTextField();
        fieldPass = new javax.swing.JTextField();
        buttonKoneksi = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Database");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 36, -1, -1));

        jLabel2.setText("User");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 74, -1, -1));

        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 115, -1, -1));

        fieldDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDBActionPerformed(evt);
            }
        });
        getContentPane().add(fieldDB, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 33, 59, -1));
        getContentPane().add(fieldUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 71, 59, -1));
        getContentPane().add(fieldPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 109, 59, -1));

        buttonKoneksi.setText("Koneksikan!");
        buttonKoneksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKoneksiActionPerformed(evt);
            }
        });
        getContentPane().add(buttonKoneksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 162, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas4/BLogin.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonKoneksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKoneksiActionPerformed
        // TODO add your handling code here:
       String i = fieldDB.getText();
       String j = fieldUser.getText();
       String k = fieldPass.getText();
           try {
                   String host        = "jdbc:mysql://localhost/"+ i,
                              user        = j,
                              pass        = k;
                   Connection con = (Connection) DriverManager.getConnection(host, user, pass);
                   JOptionPane.showMessageDialog(null, "Koneksi Berhasil");
                   
                   FrmCuaca frmCuaca = new FrmCuaca();
                   frmCuaca.setLocationRelativeTo(null);
                   frmCuaca.setVisible(true);
                  
           }catch(SQLException err){
                   JOptionPane.showMessageDialog(null,"Error");
           }
    }//GEN-LAST:event_buttonKoneksiActionPerformed

    private void fieldDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDBActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonKoneksi;
    private javax.swing.JTextField fieldDB;
    private javax.swing.JTextField fieldPass;
    private javax.swing.JTextField fieldUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
